pipeline {
    agent any
    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world!'
                bat 'cd CICD'
                bat 'setup.bat'
            }
        }
    }
}
